language: node_js

node_js:
  - '0.10'

addons:
  sauce_connect: true

before_script:
  - npm install -g selenium-standalone
  - start-selenium > /dev/null 2>&1 &
  - node test/app/scripts/web-server.js > /dev/null &